data_power <- read.table("household_power_consumption.txt", header = T, sep = ";", na.strings = "?")
head(data_power)
data_power$Date <- as.Date(data_power$Date, format="%d/%m/%Y")
data <- subset(data_power, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
head(data)
data$date_time <- strptime(paste(data$Date, data$Time), "%Y-%m-%d %H:%M:%S")
data$Date_time <- as.POSIXct(date_time)
#Plot 4
attach(data)
par(mfrow=c(2,2))
plot(Global_active_power ~ Date_time, type = "l",ylab = "Global Active Power (kilowatts)", xlab = "")
plot(Voltage~Date_time,type="l",xlab="datetime",ylab="Voltage")
with(data, {plot(Sub_metering_1~Date_time, type="l",ylab="Energy sub metering", xlab="")
  lines(Sub_metering_2~Date_time,col='Red')
  lines(Sub_metering_3~Datetime,col='Blue')
})
legend("topright",legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=1, lwd=2)
plot(Global_reactive_power~Date_time,type="l",xlab="datetime")
dev.copy(png, file = "plot4.png")
dev.off()
