data_power <- read.table("household_power_consumption.txt", header = T, sep = ";", na.strings = "?")
head(data_power)
data_power$Date <- as.Date(data_power$Date, format="%d/%m/%Y")
data <- subset(data_power, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
head(data)
data$date_time <- strptime(paste(data$Date, data$Time), "%Y-%m-%d %H:%M:%S")
data$Date_time <- as.POSIXct(date_time)
#Plot 3
attach(data)
with(data, {plot(Sub_metering_1~Date_time, type="l",ylab="Energy sub metering", xlab=" ")
  lines(Sub_metering_3~Date_time,col='Blue')
  lines(Sub_metering_2~Date_time,col='Red')})
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),col=c("black", "red", "blue"), lty=1, lwd=2)
dev.copy(png, file = "plot3.png",height = 480, width = 480)
dev.off()
